<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-module-clarizen</artifactId>
    <version>2.0.10-SNAPSHOT</version>
    <packaging>mule-module</packaging>
    <name>Clarizen Cloud Connector</name>

    <parent>
        <groupId>org.mule.tools.devkit</groupId>
        <artifactId>mule-devkit-parent</artifactId>
        <version>3.4.3</version>
    </parent>

    <properties>
        <category>Community</category>
        <devkit.studio.package.skip>false</devkit.studio.package.skip>
        <cxf.version>2.5.10</cxf.version>
        <licensePath>LICENSE.md</licensePath>
        <mule.module.cxf.version>3.9.0</mule.module.cxf.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf.version}</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                        <configuration>
                        <extension>true</extension>
                        <sourceRoot>target/generated-sources/schema</sourceRoot>
                        <wsdlOptions>
                          <wsdlOption>
                            <wsdl>src/main/resources/schema/Clarizen.wsdl</wsdl>
                            <wsdlLocation>https://api.clarizen.com/v1.0/Clarizen.svc</wsdlLocation>
                            <bindingFiles>
                                <bindingFile>src/main/resources/schema/bindings.xml</bindingFile>
                            </bindingFiles>
                        </wsdlOption>
                        </wsdlOptions>
                      </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-databinding-jaxb</artifactId>
            <version>${cxf.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.mule.modules</groupId>
          <artifactId>mule-module-cxf</artifactId>
          <version>${mule.module.cxf.version}</version>
          <scope>provided</scope>
        </dependency>
    </dependencies>


    <repositories>
        <repository>
            <id>mulesoft-releases</id>
            <name>MuleSoft Releases Repository</name>
            <url>http://repository.mulesoft.org/releases/</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>mulesoft-snapshots</id>
            <name>MuleSoft Snapshots Repository</name>
            <url>http://repository.mulesoft.org/snapshots/</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <scm>
        <connection>scm:git:git://github.com:mulesoft/clarizen-connector.git</connection>
        <developerConnection>scm:git:git@github.com:mulesoft/clarizen-connector.git</developerConnection>
        <url>http://github.com/mulesoft/clarizen-connector</url>
    </scm>

</project>
